-- Xcode Plugin Integrations
-- Highlight groups for popular Neovim plugins

local M = {}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.setup(palette, opts)
  local p = palette
  local config = opts or {}
  local transparent = config.transparent or false
  local bg = transparent and p.none or p.bg
  local bg_sidebar = transparent and p.none or p.bg_sidebar
  local bg_float = transparent and p.none or p.bg_float

  -----------------------------------------------------------------------------
  -- Telescope
  -----------------------------------------------------------------------------
  hl("TelescopeNormal", { fg = p.fg, bg = bg_float })
  hl("TelescopeBorder", { fg = p.border, bg = bg_float })
  hl("TelescopeTitle", { fg = p.fg_dark })
  hl("TelescopePromptNormal", { fg = p.fg, bg = p.bg_highlight })
  hl("TelescopePromptBorder", { fg = p.border, bg = p.bg_highlight })
  hl("TelescopePromptTitle", { fg = p.fg_dark })
  hl("TelescopePromptPrefix", { fg = p.pink })
  hl("TelescopePromptCounter", { fg = p.comment })
  hl("TelescopeResultsNormal", { fg = p.fg, bg = bg_float })
  hl("TelescopeResultsBorder", { fg = p.border, bg = bg_float })
  hl("TelescopeResultsTitle", { fg = p.fg_dark })
  hl("TelescopePreviewNormal", { fg = p.fg, bg = bg_float })
  hl("TelescopePreviewBorder", { fg = p.border, bg = bg_float })
  hl("TelescopePreviewTitle", { fg = p.fg_dark })
  hl("TelescopeSelection", { bg = p.bg_visual })
  hl("TelescopeSelectionCaret", { fg = p.pink, bg = p.bg_visual })
  hl("TelescopeMultiSelection", { fg = p.cyan, bg = p.bg_visual })
  hl("TelescopeMultiIcon", { fg = p.cyan })
  hl("TelescopeMatching", { fg = p.orange })

  -----------------------------------------------------------------------------
  -- Neo-tree
  -----------------------------------------------------------------------------
  hl("NeoTreeNormal", { fg = p.fg_sidebar, bg = bg_sidebar })
  hl("NeoTreeNormalNC", { fg = p.fg_sidebar, bg = bg_sidebar })
  hl("NeoTreeVertSplit", { fg = p.border, bg = bg_sidebar })
  hl("NeoTreeWinSeparator", { fg = p.border, bg = bg_sidebar })
  hl("NeoTreeEndOfBuffer", { fg = bg_sidebar, bg = bg_sidebar })
  hl("NeoTreeRootName", { fg = p.fg_dark })
  hl("NeoTreeFileName", { fg = p.fg_sidebar })
  hl("NeoTreeFileNameOpened", { fg = p.fg })
  hl("NeoTreeIndentMarker", { fg = p.fg_gutter })
  hl("NeoTreeGitAdded", { fg = p.git_add })
  hl("NeoTreeGitConflict", { fg = p.orange })
  hl("NeoTreeGitDeleted", { fg = p.git_delete })
  hl("NeoTreeGitIgnored", { fg = p.fg_gutter })
  hl("NeoTreeGitModified", { fg = p.git_change })
  hl("NeoTreeGitUnstaged", { fg = p.git_change })
  hl("NeoTreeGitUntracked", { fg = p.green })
  hl("NeoTreeGitStaged", { fg = p.git_add })
  hl("NeoTreeFloatBorder", { fg = p.border, bg = bg_float })
  hl("NeoTreeFloatTitle", { fg = p.fg_dark, bg = bg_float })
  hl("NeoTreeTitleBar", { fg = p.fg_dark, bg = p.bg_highlight })
  hl("NeoTreeDirectoryName", { fg = p.cyan })
  hl("NeoTreeDirectoryIcon", { fg = p.cyan })
  hl("NeoTreeSymbolicLinkTarget", { fg = p.purple })
  hl("NeoTreeFilterTerm", { fg = p.orange, bold = true })
  hl("NeoTreeModified", { fg = p.orange })
  hl("NeoTreeDimText", { fg = p.fg_gutter })
  hl("NeoTreeDotfile", { fg = p.comment })
  hl("NeoTreeHiddenByName", { fg = p.comment })
  hl("NeoTreeCursorLine", { bg = p.bg_highlight })

  -----------------------------------------------------------------------------
  -- nvim-tree
  -----------------------------------------------------------------------------
  hl("NvimTreeNormal", { fg = p.fg_sidebar, bg = bg_sidebar })
  hl("NvimTreeNormalNC", { fg = p.fg_sidebar, bg = bg_sidebar })
  hl("NvimTreeRootFolder", { fg = p.pink, bold = true })
  hl("NvimTreeFolderIcon", { fg = p.cyan })
  hl("NvimTreeFolderName", { fg = p.cyan })
  hl("NvimTreeOpenedFolderName", { fg = p.cyan })
  hl("NvimTreeEmptyFolderName", { fg = p.comment })
  hl("NvimTreeIndentMarker", { fg = p.fg_gutter })
  hl("NvimTreeGitDirty", { fg = p.git_change })
  hl("NvimTreeGitNew", { fg = p.git_add })
  hl("NvimTreeGitDeleted", { fg = p.git_delete })
  hl("NvimTreeGitStaged", { fg = p.git_add })
  hl("NvimTreeSpecialFile", { fg = p.yellow })
  hl("NvimTreeImageFile", { fg = p.fg })
  hl("NvimTreeSymlink", { fg = p.purple })
  hl("NvimTreeWinSeparator", { fg = p.border, bg = bg_sidebar })
  hl("NvimTreeEndOfBuffer", { fg = bg_sidebar })

  -----------------------------------------------------------------------------
  -- Gitsigns
  -----------------------------------------------------------------------------
  hl("GitSignsAdd", { fg = p.git_add })
  hl("GitSignsChange", { fg = p.git_change })
  hl("GitSignsDelete", { fg = p.git_delete })
  hl("GitSignsAddNr", { fg = p.git_add })
  hl("GitSignsChangeNr", { fg = p.git_change })
  hl("GitSignsDeleteNr", { fg = p.git_delete })
  hl("GitSignsAddLn", { bg = p.diff_add })
  hl("GitSignsChangeLn", { bg = p.diff_change })
  hl("GitSignsDeleteLn", { bg = p.diff_delete })
  hl("GitSignsAddInline", { bg = p.diff_add })
  hl("GitSignsChangeInline", { bg = p.diff_change })
  hl("GitSignsDeleteInline", { bg = p.diff_delete })
  hl("GitSignsAddPreview", { fg = p.git_add })
  hl("GitSignsDeletePreview", { fg = p.git_delete })
  hl("GitSignsCurrentLineBlame", { fg = p.comment })
  hl("GitSignsAddVirtLn", { fg = p.git_add })
  hl("GitSignsDeleteVirtLn", { fg = p.git_delete })

  -----------------------------------------------------------------------------
  -- nvim-cmp
  -----------------------------------------------------------------------------
  hl("CmpItemAbbr", { fg = p.fg })
  hl("CmpItemAbbrDeprecated", { fg = p.comment, strikethrough = true })
  hl("CmpItemAbbrMatch", { fg = p.cyan })
  hl("CmpItemAbbrMatchFuzzy", { fg = p.cyan })
  hl("CmpItemKind", { fg = p.purple })
  hl("CmpItemKindClass", { fg = p.cyan })
  hl("CmpItemKindColor", { fg = p.yellow })
  hl("CmpItemKindConstant", { fg = p.yellow })
  hl("CmpItemKindConstructor", { fg = p.cyan })
  hl("CmpItemKindEnum", { fg = p.cyan })
  hl("CmpItemKindEnumMember", { fg = p.yellow })
  hl("CmpItemKindEvent", { fg = p.orange })
  hl("CmpItemKindField", { fg = p.green })
  hl("CmpItemKindFile", { fg = p.fg })
  hl("CmpItemKindFolder", { fg = p.cyan })
  hl("CmpItemKindFunction", { fg = p.purple })
  hl("CmpItemKindInterface", { fg = p.lavender })
  hl("CmpItemKindKeyword", { fg = p.pink })
  hl("CmpItemKindMethod", { fg = p.purple })
  hl("CmpItemKindModule", { fg = p.lavender })
  hl("CmpItemKindOperator", { fg = p.fg })
  hl("CmpItemKindProperty", { fg = p.green })
  hl("CmpItemKindReference", { fg = p.cyan })
  hl("CmpItemKindSnippet", { fg = p.orange })
  hl("CmpItemKindStruct", { fg = p.cyan })
  hl("CmpItemKindText", { fg = p.fg })
  hl("CmpItemKindTypeParameter", { fg = p.lavender })
  hl("CmpItemKindUnit", { fg = p.yellow })
  hl("CmpItemKindValue", { fg = p.yellow })
  hl("CmpItemKindVariable", { fg = p.fg })
  hl("CmpItemKindCopilot", { fg = p.green })
  hl("CmpItemKindCodeium", { fg = p.green })
  hl("CmpItemMenu", { fg = p.comment })

  -----------------------------------------------------------------------------
  -- blink.cmp
  -----------------------------------------------------------------------------
  hl("BlinkCmpMenu", { fg = p.fg, bg = bg_float })
  hl("BlinkCmpMenuBorder", { fg = p.border, bg = bg_float })
  hl("BlinkCmpMenuSelection", { bg = p.bg_visual })
  hl("BlinkCmpLabel", { fg = p.fg })
  hl("BlinkCmpLabelDeprecated", { fg = p.comment, strikethrough = true })
  hl("BlinkCmpLabelMatch", { fg = p.cyan })
  hl("BlinkCmpKind", { fg = p.purple })
  hl("BlinkCmpKindClass", { fg = p.cyan })
  hl("BlinkCmpKindFunction", { fg = p.purple })
  hl("BlinkCmpKindMethod", { fg = p.purple })
  hl("BlinkCmpKindVariable", { fg = p.fg })
  hl("BlinkCmpKindKeyword", { fg = p.pink })
  hl("BlinkCmpKindText", { fg = p.fg })
  hl("BlinkCmpKindSnippet", { fg = p.orange })

  -----------------------------------------------------------------------------
  -- Which-key
  -----------------------------------------------------------------------------
  hl("WhichKey", { fg = p.pink })
  hl("WhichKeyGroup", { fg = p.cyan })
  hl("WhichKeyDesc", { fg = p.fg })
  hl("WhichKeySeparator", { fg = p.comment })
  hl("WhichKeyFloat", { bg = bg_float })
  hl("WhichKeyBorder", { fg = p.border, bg = bg_float })
  hl("WhichKeyValue", { fg = p.comment })

  -----------------------------------------------------------------------------
  -- Indent Blankline
  -----------------------------------------------------------------------------
  hl("IblIndent", { fg = p.fg_gutter })
  hl("IblScope", { fg = p.purple })
  hl("IndentBlanklineChar", { fg = p.fg_gutter })
  hl("IndentBlanklineSpaceChar", { fg = p.fg_gutter })
  hl("IndentBlanklineSpaceCharBlankline", { fg = p.fg_gutter })
  hl("IndentBlanklineContextChar", { fg = p.purple })
  hl("IndentBlanklineContextStart", { sp = p.purple, underline = true })

  -----------------------------------------------------------------------------
  -- Dashboard
  -----------------------------------------------------------------------------
  hl("DashboardHeader", { fg = p.pink })
  hl("DashboardFooter", { fg = p.comment })
  hl("DashboardCenter", { fg = p.cyan })
  hl("DashboardShortCut", { fg = p.orange })
  hl("DashboardKey", { fg = p.orange })
  hl("DashboardDesc", { fg = p.fg })
  hl("DashboardIcon", { fg = p.cyan })
  hl("DashboardMruTitle", { fg = p.pink })
  hl("DashboardProjectTitle", { fg = p.pink })
  hl("DashboardFiles", { fg = p.fg })

  -----------------------------------------------------------------------------
  -- Alpha
  -----------------------------------------------------------------------------
  hl("AlphaHeader", { fg = p.pink })
  hl("AlphaButtons", { fg = p.cyan })
  hl("AlphaShortcut", { fg = p.orange })
  hl("AlphaFooter", { fg = p.comment })

  -----------------------------------------------------------------------------
  -- Lazy.nvim
  -----------------------------------------------------------------------------
  hl("LazyH1", { fg = p.fg, bg = p.bg_highlight })
  hl("LazyH2", { fg = p.pink })
  hl("LazyButton", { fg = p.fg, bg = p.bg_highlight })
  hl("LazyButtonActive", { fg = p.fg, bg = p.bg_visual })
  hl("LazyComment", { fg = p.comment })
  hl("LazyCommit", { fg = p.comment })
  hl("LazyCommitIssue", { fg = p.orange })
  hl("LazyCommitScope", { fg = p.fg })
  hl("LazyCommitType", { fg = p.cyan })
  hl("LazyDir", { fg = p.cyan })
  hl("LazyNoCond", { fg = p.error })
  hl("LazyProgressDone", { fg = p.pink })
  hl("LazyProgressTodo", { fg = p.fg_gutter })
  hl("LazyProp", { fg = p.green })
  hl("LazyReasonCmd", { fg = p.purple })
  hl("LazyReasonEvent", { fg = p.yellow })
  hl("LazyReasonFt", { fg = p.cyan })
  hl("LazyReasonImport", { fg = p.lavender })
  hl("LazyReasonKeys", { fg = p.pink })
  hl("LazyReasonPlugin", { fg = p.green })
  hl("LazyReasonRuntime", { fg = p.orange })
  hl("LazyReasonSource", { fg = p.fg })
  hl("LazyReasonStart", { fg = p.green })
  hl("LazySpecial", { fg = p.orange })
  hl("LazyTaskOutput", { fg = p.fg })
  hl("LazyUrl", { fg = p.cyan, underline = true })
  hl("LazyValue", { fg = p.green })

  -----------------------------------------------------------------------------
  -- Mason
  -----------------------------------------------------------------------------
  hl("MasonHeader", { fg = p.fg, bg = p.bg_highlight })
  hl("MasonHeaderSecondary", { fg = p.fg, bg = p.bg_highlight })
  hl("MasonHighlight", { fg = p.cyan })
  hl("MasonHighlightBlock", { fg = p.fg, bg = p.bg_visual })
  hl("MasonHighlightBlockBold", { fg = p.fg, bg = p.bg_visual })
  hl("MasonHighlightSecondary", { fg = p.orange })
  hl("MasonMuted", { fg = p.comment })
  hl("MasonMutedBlock", { fg = p.fg_dark, bg = p.bg_highlight })

  -----------------------------------------------------------------------------
  -- Bufferline
  -----------------------------------------------------------------------------
  hl("BufferLineFill", { bg = p.bg_dark })
  hl("BufferLineBackground", { fg = p.comment, bg = p.bg_dark })
  hl("BufferLineBuffer", { fg = p.comment, bg = p.bg_dark })
  hl("BufferLineBufferSelected", { fg = p.fg, bg = bg })
  hl("BufferLineBufferVisible", { fg = p.fg_dark, bg = bg })
  hl("BufferLineCloseButton", { fg = p.comment, bg = p.bg_dark })
  hl("BufferLineCloseButtonSelected", { fg = p.error, bg = bg })
  hl("BufferLineCloseButtonVisible", { fg = p.comment, bg = bg })
  hl("BufferLineDevIconLuaSelected", { bg = bg })
  hl("BufferLineDiagnostic", { fg = p.comment, bg = p.bg_dark })
  hl("BufferLineDiagnosticSelected", { fg = p.fg, bg = bg })
  hl("BufferLineDiagnosticVisible", { fg = p.fg_dark, bg = bg })
  hl("BufferLineDuplicate", { fg = p.comment, bg = p.bg_dark, italic = true })
  hl("BufferLineDuplicateSelected", { fg = p.fg, bg = bg, italic = true })
  hl("BufferLineDuplicateVisible", { fg = p.fg_dark, bg = bg, italic = true })
  hl("BufferLineError", { fg = p.error, bg = p.bg_dark })
  hl("BufferLineErrorDiagnostic", { fg = p.error, bg = p.bg_dark })
  hl("BufferLineErrorSelected", { fg = p.error, bg = bg })
  hl("BufferLineHint", { fg = p.hint, bg = p.bg_dark })
  hl("BufferLineHintDiagnostic", { fg = p.hint, bg = p.bg_dark })
  hl("BufferLineHintSelected", { fg = p.hint, bg = bg })
  hl("BufferLineIndicatorSelected", { fg = p.pink, bg = bg })
  hl("BufferLineIndicatorVisible", { fg = p.fg_gutter, bg = bg })
  hl("BufferLineInfo", { fg = p.info, bg = p.bg_dark })
  hl("BufferLineInfoDiagnostic", { fg = p.info, bg = p.bg_dark })
  hl("BufferLineInfoSelected", { fg = p.info, bg = bg })
  hl("BufferLineModified", { fg = p.orange, bg = p.bg_dark })
  hl("BufferLineModifiedSelected", { fg = p.orange, bg = bg })
  hl("BufferLineModifiedVisible", { fg = p.orange, bg = bg })
  hl("BufferLineNumbers", { fg = p.comment, bg = p.bg_dark })
  hl("BufferLineNumbersSelected", { fg = p.fg, bg = bg })
  hl("BufferLineNumbersVisible", { fg = p.fg_dark, bg = bg })
  hl("BufferLineOffset", { fg = p.fg, bg = bg_sidebar })
  hl("BufferLinePick", { fg = p.pink, bg = p.bg_dark })
  hl("BufferLinePickSelected", { fg = p.pink, bg = bg })
  hl("BufferLinePickVisible", { fg = p.pink, bg = bg })
  hl("BufferLineSeparator", { fg = p.bg_dark, bg = p.bg_dark })
  hl("BufferLineSeparatorSelected", { fg = p.bg_dark, bg = bg })
  hl("BufferLineSeparatorVisible", { fg = p.bg_dark, bg = bg })
  hl("BufferLineTab", { fg = p.comment, bg = p.bg_dark })
  hl("BufferLineTabSelected", { fg = p.fg, bg = bg })
  hl("BufferLineTabClose", { fg = p.error, bg = p.bg_dark })
  hl("BufferLineWarning", { fg = p.warning, bg = p.bg_dark })
  hl("BufferLineWarningDiagnostic", { fg = p.warning, bg = p.bg_dark })
  hl("BufferLineWarningSelected", { fg = p.warning, bg = bg })

  -----------------------------------------------------------------------------
  -- Lualine (expose colors for lualine theme)
  -----------------------------------------------------------------------------
  hl("LualineNormal", { fg = p.bg, bg = p.pink })
  hl("LualineInsert", { fg = p.bg, bg = p.green })
  hl("LualineVisual", { fg = p.bg, bg = p.purple })
  hl("LualineReplace", { fg = p.bg, bg = p.red })
  hl("LualineCommand", { fg = p.bg, bg = p.orange })
  hl("LualineInactive", { fg = p.comment, bg = p.bg_statusline })

  -----------------------------------------------------------------------------
  -- Noice
  -----------------------------------------------------------------------------
  hl("NoiceCmdline", { fg = p.fg })
  hl("NoiceCmdlineIcon", { fg = p.pink })
  hl("NoiceCmdlineIconSearch", { fg = p.orange })
  hl("NoiceCmdlinePopup", { fg = p.fg, bg = bg_float })
  hl("NoiceCmdlinePopupBorder", { fg = p.border, bg = bg_float })
  hl("NoiceCmdlinePopupBorderSearch", { fg = p.orange, bg = bg_float })
  hl("NoiceConfirm", { fg = p.fg, bg = bg_float })
  hl("NoiceConfirmBorder", { fg = p.pink, bg = bg_float })
  hl("NoiceFormatConfirm", { fg = p.pink })
  hl("NoiceFormatConfirmDefault", { fg = p.fg, bg = p.bg_visual })
  hl("NoiceMini", { fg = p.fg, bg = p.bg_statusline })
  hl("NoicePopup", { fg = p.fg, bg = bg_float })
  hl("NoicePopupBorder", { fg = p.border, bg = bg_float })
  hl("NoiceScrollbar", { bg = p.bg_popup })
  hl("NoiceScrollbarThumb", { bg = p.fg_gutter })
  hl("NoiceVirtualText", { fg = p.info })

  -----------------------------------------------------------------------------
  -- Notify
  -----------------------------------------------------------------------------
  hl("NotifyBackground", { bg = bg })
  hl("NotifyDEBUGBody", { fg = p.fg })
  hl("NotifyDEBUGBorder", { fg = p.comment })
  hl("NotifyDEBUGIcon", { fg = p.comment })
  hl("NotifyDEBUGTitle", { fg = p.comment })
  hl("NotifyERRORBody", { fg = p.fg })
  hl("NotifyERRORBorder", { fg = p.error })
  hl("NotifyERRORIcon", { fg = p.error })
  hl("NotifyERRORTitle", { fg = p.error })
  hl("NotifyINFOBody", { fg = p.fg })
  hl("NotifyINFOBorder", { fg = p.info })
  hl("NotifyINFOIcon", { fg = p.info })
  hl("NotifyINFOTitle", { fg = p.info })
  hl("NotifyTRACEBody", { fg = p.fg })
  hl("NotifyTRACEBorder", { fg = p.purple })
  hl("NotifyTRACEIcon", { fg = p.purple })
  hl("NotifyTRACETitle", { fg = p.purple })
  hl("NotifyWARNBody", { fg = p.fg })
  hl("NotifyWARNBorder", { fg = p.warning })
  hl("NotifyWARNIcon", { fg = p.warning })
  hl("NotifyWARNTitle", { fg = p.warning })

  -----------------------------------------------------------------------------
  -- Flash.nvim
  -----------------------------------------------------------------------------
  hl("FlashBackdrop", { fg = p.comment })
  hl("FlashCurrent", { bg = p.bg_search })
  hl("FlashLabel", { fg = p.bg, bg = p.pink })
  hl("FlashMatch", { bg = p.bg_visual })
  hl("FlashCursor", { reverse = true })

  -----------------------------------------------------------------------------
  -- Leap.nvim
  -----------------------------------------------------------------------------
  hl("LeapMatch", { fg = p.fg, bg = p.bg_visual })
  hl("LeapLabelPrimary", { fg = p.bg, bg = p.pink })
  hl("LeapLabelSecondary", { fg = p.bg, bg = p.cyan })
  hl("LeapBackdrop", { fg = p.comment })

  -----------------------------------------------------------------------------
  -- mini.nvim
  -----------------------------------------------------------------------------
  hl("MiniCompletionActiveParameter", { underline = true })
  hl("MiniCursorword", { bg = p.bg_visual })
  hl("MiniCursorwordCurrent", { bg = p.bg_visual })
  hl("MiniFilesNormal", { fg = p.fg, bg = bg_float })
  hl("MiniFilesBorder", { fg = p.border, bg = bg_float })
  hl("MiniFilesTitle", { fg = p.fg_dark })
  hl("MiniFilesTitleFocused", { fg = p.fg, bg = bg_float })
  hl("MiniHipatternsFixme", { fg = p.error, bg = p.diff_delete })
  hl("MiniHipatternsHack", { fg = p.warning, bg = p.diff_change })
  hl("MiniHipatternsNote", { fg = p.info, bg = p.bg_highlight })
  hl("MiniHipatternsTodo", { fg = p.yellow, bg = p.bg_highlight })
  hl("MiniIconsAzure", { fg = p.cyan })
  hl("MiniIconsBlue", { fg = p.blue })
  hl("MiniIconsCyan", { fg = p.cyan })
  hl("MiniIconsGreen", { fg = p.green })
  hl("MiniIconsGrey", { fg = p.comment })
  hl("MiniIconsOrange", { fg = p.orange })
  hl("MiniIconsPurple", { fg = p.purple })
  hl("MiniIconsRed", { fg = p.red })
  hl("MiniIconsYellow", { fg = p.yellow })
  hl("MiniIndentscopeSymbol", { fg = p.purple })
  hl("MiniIndentscopePrefix", { nocombine = true })
  hl("MiniJump", { fg = p.bg, bg = p.pink })
  hl("MiniJump2dDim", { fg = p.comment })
  hl("MiniJump2dSpot", { fg = p.bg, bg = p.pink })
  hl("MiniJump2dSpotAhead", { fg = p.bg, bg = p.cyan })
  hl("MiniJump2dSpotUnique", { fg = p.bg, bg = p.orange })
  hl("MiniMapNormal", { fg = p.fg, bg = bg_sidebar })
  hl("MiniMapSymbolCount", { fg = p.purple })
  hl("MiniMapSymbolLine", { fg = p.cyan })
  hl("MiniMapSymbolView", { fg = p.fg_gutter })
  hl("MiniNotifyBorder", { fg = p.border, bg = bg_float })
  hl("MiniNotifyNormal", { fg = p.fg, bg = bg_float })
  hl("MiniNotifyTitle", { fg = p.fg_dark })
  hl("MiniPickBorder", { fg = p.border, bg = bg_float })
  hl("MiniPickBorderBusy", { fg = p.warning, bg = bg_float })
  hl("MiniPickBorderText", { fg = p.pink, bg = bg_float })
  hl("MiniPickIconDirectory", { fg = p.cyan })
  hl("MiniPickIconFile", { fg = p.fg })
  hl("MiniPickHeader", { fg = p.fg_dark })
  hl("MiniPickMatchCurrent", { bg = p.bg_visual })
  hl("MiniPickMatchMarked", { bg = p.bg_search })
  hl("MiniPickMatchRanges", { fg = p.cyan })
  hl("MiniPickNormal", { fg = p.fg, bg = bg_float })
  hl("MiniPickPreviewLine", { bg = p.bg_visual })
  hl("MiniPickPreviewRegion", { bg = p.bg_search })
  hl("MiniPickPrompt", { fg = p.pink, bg = bg_float })
  hl("MiniStarterCurrent", { nocombine = true })
  hl("MiniStarterFooter", { fg = p.comment, italic = true })
  hl("MiniStarterHeader", { fg = p.pink })
  hl("MiniStarterInactive", { fg = p.comment })
  hl("MiniStarterItem", { fg = p.fg })
  hl("MiniStarterItemBullet", { fg = p.border })
  hl("MiniStarterItemPrefix", { fg = p.orange })
  hl("MiniStarterQuery", { fg = p.cyan })
  hl("MiniStarterSection", { fg = p.pink })
  hl("MiniStatuslineDevinfo", { fg = p.fg, bg = p.bg_highlight })
  hl("MiniStatuslineFileinfo", { fg = p.fg, bg = p.bg_highlight })
  hl("MiniStatuslineFilename", { fg = p.comment, bg = p.bg_statusline })
  hl("MiniStatuslineInactive", { fg = p.comment, bg = p.bg_statusline })
  hl("MiniStatuslineModeCommand", { fg = p.bg, bg = p.orange })
  hl("MiniStatuslineModeInsert", { fg = p.bg, bg = p.green })
  hl("MiniStatuslineModeNormal", { fg = p.bg, bg = p.pink })
  hl("MiniStatuslineModeOther", { fg = p.bg, bg = p.cyan })
  hl("MiniStatuslineModeReplace", { fg = p.bg, bg = p.red })
  hl("MiniStatuslineModeVisual", { fg = p.bg, bg = p.purple })
  hl("MiniSurround", { fg = p.bg, bg = p.orange })
  hl("MiniTablineCurrent", { fg = p.fg, bg = bg })
  hl("MiniTablineFill", { bg = p.bg_dark })
  hl("MiniTablineHidden", { fg = p.comment, bg = p.bg_dark })
  hl("MiniTablineModifiedCurrent", { fg = p.orange, bg = bg })
  hl("MiniTablineModifiedHidden", { fg = p.orange, bg = p.bg_dark })
  hl("MiniTablineModifiedVisible", { fg = p.orange, bg = bg })
  hl("MiniTablineTabpagesection", { fg = p.fg, bg = p.bg_highlight })
  hl("MiniTablineVisible", { fg = p.fg, bg = bg })
  hl("MiniTestEmphasis", {})
  hl("MiniTestFail", { fg = p.error })
  hl("MiniTestPass", { fg = p.green })
  hl("MiniTrailspace", { bg = p.error })

  -----------------------------------------------------------------------------
  -- Todo Comments
  -----------------------------------------------------------------------------
  hl("TodoBgFIX", { fg = p.error, bg = p.diff_delete })
  hl("TodoBgHACK", { fg = p.warning, bg = p.diff_change })
  hl("TodoBgNOTE", { fg = p.info, bg = p.bg_highlight })
  hl("TodoBgPERF", { fg = p.purple, bg = p.bg_highlight })
  hl("TodoBgTEST", { fg = p.purple, bg = p.bg_highlight })
  hl("TodoBgTODO", { fg = p.yellow, bg = p.bg_highlight })
  hl("TodoBgWARN", { fg = p.warning, bg = p.diff_change })
  hl("TodoFgFIX", { fg = p.error })
  hl("TodoFgHACK", { fg = p.warning })
  hl("TodoFgNOTE", { fg = p.info })
  hl("TodoFgPERF", { fg = p.purple })
  hl("TodoFgTEST", { fg = p.purple })
  hl("TodoFgTODO", { fg = p.yellow })
  hl("TodoFgWARN", { fg = p.warning })
  hl("TodoSignFIX", { fg = p.error })
  hl("TodoSignHACK", { fg = p.warning })
  hl("TodoSignNOTE", { fg = p.info })
  hl("TodoSignPERF", { fg = p.purple })
  hl("TodoSignTEST", { fg = p.purple })
  hl("TodoSignTODO", { fg = p.yellow })
  hl("TodoSignWARN", { fg = p.warning })

  -----------------------------------------------------------------------------
  -- Trouble
  -----------------------------------------------------------------------------
  hl("TroubleCount", { fg = p.purple })
  hl("TroubleFile", { fg = p.fg })
  hl("TroubleFoldIcon", { fg = p.pink })
  hl("TroubleIndent", { fg = p.fg_gutter })
  hl("TroubleLocation", { fg = p.comment })
  hl("TroubleNormal", { fg = p.fg, bg = bg_sidebar })
  hl("TroublePreview", { bg = p.bg_visual })
  hl("TroubleSignError", { fg = p.error })
  hl("TroubleSignHint", { fg = p.hint })
  hl("TroubleSignInformation", { fg = p.info })
  hl("TroubleSignOther", { fg = p.purple })
  hl("TroubleSignWarning", { fg = p.warning })
  hl("TroubleSource", { fg = p.comment })
  hl("TroubleText", { fg = p.fg })

  -----------------------------------------------------------------------------
  -- nvim-dap
  -----------------------------------------------------------------------------
  hl("DapBreakpoint", { fg = p.error })
  hl("DapBreakpointCondition", { fg = p.warning })
  hl("DapBreakpointRejected", { fg = p.comment })
  hl("DapLogPoint", { fg = p.info })
  hl("DapStopped", { fg = p.yellow })

  -----------------------------------------------------------------------------
  -- nvim-dap-ui
  -----------------------------------------------------------------------------
  hl("DapUIBreakpointsCurrentLine", { fg = p.yellow })
  hl("DapUIBreakpointsDisabledLine", { fg = p.comment })
  hl("DapUIBreakpointsInfo", { fg = p.info })
  hl("DapUIBreakpointsLine", { fg = p.pink })
  hl("DapUIBreakpointsPath", { fg = p.cyan })
  hl("DapUIDecoration", { fg = p.pink })
  hl("DapUIFloatBorder", { fg = p.border })
  hl("DapUILineNumber", { fg = p.pink })
  hl("DapUIModifiedValue", { fg = p.orange })
  hl("DapUIPlayPause", { fg = p.green })
  hl("DapUIPlayPauseNC", { fg = p.green })
  hl("DapUIRestart", { fg = p.green })
  hl("DapUIRestartNC", { fg = p.green })
  hl("DapUIScope", { fg = p.pink })
  hl("DapUISource", { fg = p.purple })
  hl("DapUIStepBack", { fg = p.cyan })
  hl("DapUIStepBackNC", { fg = p.cyan })
  hl("DapUIStepInto", { fg = p.cyan })
  hl("DapUIStepIntoNC", { fg = p.cyan })
  hl("DapUIStepOut", { fg = p.cyan })
  hl("DapUIStepOutNC", { fg = p.cyan })
  hl("DapUIStepOver", { fg = p.cyan })
  hl("DapUIStepOverNC", { fg = p.cyan })
  hl("DapUIStop", { fg = p.error })
  hl("DapUIStopNC", { fg = p.error })
  hl("DapUIStoppedThread", { fg = p.cyan })
  hl("DapUIThread", { fg = p.green })
  hl("DapUIType", { fg = p.lavender })
  hl("DapUIUnavailable", { fg = p.comment })
  hl("DapUIUnavailableNC", { fg = p.comment })
  hl("DapUIValue", { fg = p.fg })
  hl("DapUIVariable", { fg = p.fg })
  hl("DapUIWatchesEmpty", { fg = p.comment })
  hl("DapUIWatchesError", { fg = p.error })
  hl("DapUIWatchesValue", { fg = p.green })

  -----------------------------------------------------------------------------
  -- Aerial
  -----------------------------------------------------------------------------
  hl("AerialArrayIcon", { fg = p.orange })
  hl("AerialBooleanIcon", { fg = p.orange })
  hl("AerialClassIcon", { fg = p.cyan })
  hl("AerialConstantIcon", { fg = p.yellow })
  hl("AerialConstructorIcon", { fg = p.cyan })
  hl("AerialEnumIcon", { fg = p.cyan })
  hl("AerialEnumMemberIcon", { fg = p.yellow })
  hl("AerialEventIcon", { fg = p.orange })
  hl("AerialFieldIcon", { fg = p.green })
  hl("AerialFileIcon", { fg = p.fg })
  hl("AerialFunctionIcon", { fg = p.purple })
  hl("AerialGuide", { fg = p.fg_gutter })
  hl("AerialInterfaceIcon", { fg = p.lavender })
  hl("AerialKeyIcon", { fg = p.pink })
  hl("AerialLine", { fg = p.purple })
  hl("AerialMethodIcon", { fg = p.purple })
  hl("AerialModuleIcon", { fg = p.lavender })
  hl("AerialNamespaceIcon", { fg = p.lavender })
  hl("AerialNormal", { fg = p.fg, bg = bg_sidebar })
  hl("AerialNullIcon", { fg = p.orange })
  hl("AerialNumberIcon", { fg = p.yellow })
  hl("AerialObjectIcon", { fg = p.orange })
  hl("AerialOperatorIcon", { fg = p.fg })
  hl("AerialPackageIcon", { fg = p.lavender })
  hl("AerialPropertyIcon", { fg = p.green })
  hl("AerialStringIcon", { fg = p.red })
  hl("AerialStructIcon", { fg = p.cyan })
  hl("AerialTypeParameterIcon", { fg = p.lavender })
  hl("AerialVariableIcon", { fg = p.fg })

  -----------------------------------------------------------------------------
  -- Navic / Breadcrumbs
  -----------------------------------------------------------------------------
  hl("NavicIconsArray", { fg = p.orange })
  hl("NavicIconsBoolean", { fg = p.orange })
  hl("NavicIconsClass", { fg = p.cyan })
  hl("NavicIconsConstant", { fg = p.yellow })
  hl("NavicIconsConstructor", { fg = p.cyan })
  hl("NavicIconsEnum", { fg = p.cyan })
  hl("NavicIconsEnumMember", { fg = p.yellow })
  hl("NavicIconsEvent", { fg = p.orange })
  hl("NavicIconsField", { fg = p.green })
  hl("NavicIconsFile", { fg = p.fg })
  hl("NavicIconsFunction", { fg = p.purple })
  hl("NavicIconsInterface", { fg = p.lavender })
  hl("NavicIconsKey", { fg = p.pink })
  hl("NavicIconsMethod", { fg = p.purple })
  hl("NavicIconsModule", { fg = p.lavender })
  hl("NavicIconsNamespace", { fg = p.lavender })
  hl("NavicIconsNull", { fg = p.orange })
  hl("NavicIconsNumber", { fg = p.yellow })
  hl("NavicIconsObject", { fg = p.orange })
  hl("NavicIconsOperator", { fg = p.fg })
  hl("NavicIconsPackage", { fg = p.lavender })
  hl("NavicIconsProperty", { fg = p.green })
  hl("NavicIconsString", { fg = p.red })
  hl("NavicIconsStruct", { fg = p.cyan })
  hl("NavicIconsTypeParameter", { fg = p.lavender })
  hl("NavicIconsVariable", { fg = p.fg })
  hl("NavicSeparator", { fg = p.comment })
  hl("NavicText", { fg = p.fg })

  -----------------------------------------------------------------------------
  -- LspSaga
  -----------------------------------------------------------------------------
  hl("SagaBorder", { fg = p.border, bg = bg_float })
  hl("SagaNormal", { fg = p.fg, bg = bg_float })
  hl("SagaExpand", { fg = p.pink })
  hl("SagaCollapse", { fg = p.pink })
  hl("SagaBeacon", { bg = p.purple })
  hl("ActionPreviewNormal", { fg = p.fg, bg = bg_float })
  hl("ActionPreviewBorder", { fg = p.border, bg = bg_float })
  hl("ActionPreviewTitle", { fg = p.purple })
  hl("CodeActionNormal", { fg = p.fg, bg = bg_float })
  hl("CodeActionBorder", { fg = p.border, bg = bg_float })
  hl("CodeActionText", { fg = p.fg })
  hl("CodeActionNumber", { fg = p.cyan })
  hl("FinderSelection", { fg = p.pink })
  hl("FinderFileName", { fg = p.fg })
  hl("FinderCount", { fg = p.purple })
  hl("FinderIcon", { fg = p.cyan })
  hl("FinderType", { fg = p.orange })
  hl("FinderSpinnerTitle", { fg = p.purple })
  hl("FinderSpinner", { fg = p.purple })
  hl("FinderPreviewSearch", { bg = p.bg_search })
  hl("FinderVirtText", { fg = p.comment })
  hl("FinderNormal", { fg = p.fg, bg = bg_float })
  hl("FinderBorder", { fg = p.border, bg = bg_float })
  hl("FinderPreviewBorder", { fg = p.border, bg = bg_float })
  hl("DefinitionBorder", { fg = p.border, bg = bg_float })
  hl("DefinitionNormal", { fg = p.fg, bg = bg_float })
  hl("DefinitionSearch", { bg = p.bg_search })
  hl("HoverNormal", { fg = p.fg, bg = bg_float })
  hl("HoverBorder", { fg = p.border, bg = bg_float })
  hl("RenameBorder", { fg = p.border, bg = bg_float })
  hl("RenameNormal", { fg = p.fg, bg = bg_float })
  hl("RenameMatch", { bg = p.bg_search })
  hl("DiagnosticBorder", { fg = p.border, bg = bg_float })
  hl("DiagnosticNormal", { fg = p.fg, bg = bg_float })
  hl("DiagnosticSource", { fg = p.comment })
  hl("DiagnosticPos", { fg = p.comment })
  hl("DiagnosticWord", { fg = p.fg })
  hl("CallHierarchyNormal", { fg = p.fg, bg = bg_float })
  hl("CallHierarchyBorder", { fg = p.border, bg = bg_float })
  hl("CallHierarchyIcon", { fg = p.purple })
  hl("CallHierarchyTitle", { fg = p.pink })
  hl("SagaShadow", { bg = p.bg_dark })
  hl("OutlineIndent", { fg = p.fg_gutter })
  hl("OutlinePreviewBorder", { fg = p.border, bg = bg_float })
  hl("OutlinePreviewNormal", { fg = p.fg, bg = bg_float })
  hl("TerminalBorder", { fg = p.border, bg = bg_float })
  hl("TerminalNormal", { fg = p.fg, bg = bg_float })

  -----------------------------------------------------------------------------
  -- Spectre
  -----------------------------------------------------------------------------
  hl("SpectreHeader", { fg = p.comment })
  hl("SpectreBody", { fg = p.fg })
  hl("SpectreFile", { fg = p.cyan })
  hl("SpectreDir", { fg = p.comment })
  hl("SpectreSearch", { bg = p.diff_delete })
  hl("SpectreBorder", { fg = p.border })
  hl("SpectreReplace", { bg = p.diff_add })

  -----------------------------------------------------------------------------
  -- Illuminate
  -----------------------------------------------------------------------------
  hl("IlluminatedWordText", { bg = p.bg_visual })
  hl("IlluminatedWordRead", { bg = p.bg_visual })
  hl("IlluminatedWordWrite", { bg = p.bg_visual })

  -----------------------------------------------------------------------------
  -- Scrollbar
  -----------------------------------------------------------------------------
  hl("ScrollbarHandle", { bg = p.bg_highlight })
  hl("ScrollbarSearchHandle", { fg = p.orange, bg = p.bg_highlight })
  hl("ScrollbarSearch", { fg = p.orange })
  hl("ScrollbarErrorHandle", { fg = p.error, bg = p.bg_highlight })
  hl("ScrollbarError", { fg = p.error })
  hl("ScrollbarWarnHandle", { fg = p.warning, bg = p.bg_highlight })
  hl("ScrollbarWarn", { fg = p.warning })
  hl("ScrollbarInfoHandle", { fg = p.info, bg = p.bg_highlight })
  hl("ScrollbarInfo", { fg = p.info })
  hl("ScrollbarHintHandle", { fg = p.hint, bg = p.bg_highlight })
  hl("ScrollbarHint", { fg = p.hint })
  hl("ScrollbarMiscHandle", { fg = p.purple, bg = p.bg_highlight })
  hl("ScrollbarMisc", { fg = p.purple })

  -----------------------------------------------------------------------------
  -- nvim-ufo (fold preview)
  -----------------------------------------------------------------------------
  hl("UfoFoldedBg", { bg = p.bg_float })
  hl("UfoFoldedFg", { fg = p.fg })
  hl("UfoFoldedEllipsis", { fg = p.comment })
  hl("UfoCursorFoldedLine", { bg = p.bg_highlight })
  hl("UfoPreviewSbar", { bg = p.bg_float })
  hl("UfoPreviewThumb", { bg = p.fg_gutter })
  hl("UfoPreviewWinBar", { fg = p.fg, bg = p.bg_highlight })
  hl("UfoPreviewCursorLine", { bg = p.bg_visual })
  hl("UfoFoldedBg", { bg = p.bg_float })

  return M
end

return M
